---
- name: Deploy Ubuntu VM from VMware Content Library
  hosts: localhost
  gather_facts: no

  tasks:
    - name: Clone VM from Content Library
      community.vmware.vmware_vm_vm_drs_rules:
        hostname: "{{ vcsa-1.demo.local }}"
        username: "{{ administrator@vsphere.local }}"
        password: "{{ Password123! }}"
        validate_certs: no
        datacenter_name: "Datacenter"
        cluster_name: "Cluster"
        vm_name: "skwks-ubuntu01"
        state: poweredon
        from_vm:
          library: "SandBox-Local-Lib"
          item_name: "ubuntu_22.04"
          item_revision: "latest"  # or specify the desired revision number
        wait_for_ip_address: no
      delegate_to: localhost
