---
- name: Deploy Ubuntu VM from VMware Content Library
  hosts: localhost
  gather_facts: no

  vars:
    vcenter_hostname: "vcsa-1.demo.local"
    vcenter_username: "administrator@vsphere.local"
    vcenter_password: "Password123!"
    cluster_name: "Cluster"
    datastore_name: "vsanDatastore"
    content_library_name: "SandBox-Local-Lib"
    template_name: "ubuntu_22.04_template"
    vm_name: "skwks-ubuntu01"

  tasks:
    - name: Deploy VM from Content Library
      vmware_deploy_ovf:
        hostname: "{{ vcenter_hostname }}"
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        validate_certs: no
        cluster: "{{ cluster_name }}"
        datastore: "{{ datastore_name }}"
        content_library: "{{ content_library_name }}"
        template: "{{ template_name }}"
        vm_name: "{{ vm_name }}"
        power_on: yes
      delegate_to: localhost
