---
- name: Create Kubernetes Cluster on VMware with IP Addressing
  hosts: localhost
  gather_facts: no
  vars:
    vcenter_hostname: "your-vcenter-hostname"
    vcenter_username: "your-vcenter-username"
    vcenter_password: "your-vcenter-password"
    cluster_name: "your-cluster-name"
    datastore_name: "your-datastore-name"
    network_name: "your-vm-network"
    template_name: "your-template-name"
    vm_folder: "your-vm-folder"
    vm_username: "your-vm-username"
    vm_password: "your-vm-password"
    master_ip: "master-ip-address"
    worker_ips:
      - "worker-ip-address-1"
      - "worker-ip-address-2"

  tasks:
    - name: Connect to vCenter Server
      vmware_vm_shell:
        hostname: "{{ vcenter_hostname }}"
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        validate_certs: no
        cmd: echo "Connected to vCenter"
      delegate_to: localhost
      register: vcenter_connected

    - name: Deploy Master Node VM
      vmware_guest:
        hostname: "{{ vcenter_hostname }}"
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        validate_certs: no
        cluster: "{{ cluster_name }}"
        datastore: "{{ datastore_name }}"
        folder: "{{ vm_folder }}"
        name: "k8s-master"
        state: poweredon
        guest_id: ubuntu64Guest
        hardware:
          memory_mb: 2048
          num_cpus: 2
        networks:
          - name: "{{ network_name }}"
            mac: "00:50:56:00:00:01"
            ip: "{{ master_ip }}"
            netmask: "255.255.255.0"
            gateway: "your-gateway"
            dns_servers: "your-dns-server"
        wait_for_ip_address: yes
        vm_extra_config:
          vcpu.hotadd: yes
        vmware_tools: yes
        vmware_folder_type: vm
        vmware_folder_name: "{{ vm_folder }}"
      delegate_to: localhost

    - name: Wait for Master Node to Boot
      wait_for:
        host: "{{ master_ip }}"
        port: 22
        delay: 10
        timeout: 300

    - name: Deploy Worker Node VMs
      vmware_guest:
        hostname: "{{ vcenter_hostname }}"
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        validate_certs: no
        cluster: "{{ cluster_name }}"
        datastore: "{{ datastore_name }}"
        folder: "{{ vm_folder }}"
        name: "k8s-worker-{{ loop.index }}"
        state: poweredon
        guest_id: ubuntu64Guest
        hardware:
          memory_mb: 2048
          num_cpus: 2
        networks:
          - name: "{{ network_name }}"
            mac: "00:50:56:00:00:0{{ loop.index + 1 }}"
            ip: "{{ worker_ips[loop.index] }}"
            netmask: "255.255.255.0"
            gateway: "your-gateway"
            dns_servers: "your-dns-server"
        wait_for_ip_address: yes
        vm_extra_config:
          vcpu.hotadd: yes
        vmware_tools: yes
        vmware_folder_type: vm
        vmware_folder_name: "{{ vm_folder }}"
      loop: "{{ worker_ips }}"
      delegate_to: localhost

    - name: Wait for Worker Nodes to Boot
      wait_for:
        host: "{{ item }}"
        port: 22
        delay: 10
        timeout: 300
      loop: "{{ worker_ips }}"
