---
- name: Create Kubernetes Cluster on VMware with IP Addressing
  hosts: localhost
  gather_facts: no
  vars:
    vcenter_hostname: "vcsa-1.demo.local"
    vcenter_username: "administrator@vsphere.local"
    vcenter_password: "Password123!"
    cluster_name: "Cluster"
    datastore_name: "vsanDatastore"
    network_name: "dpg-storage-data01"
    template_name: "UBUNTU22041"
    vm_folder: "VM"
    vm_username: "demouser"
    vm_password: "Password123!"
    master_ip: "192.168.1.21"
    worker_ips:
      - "192.168.1.22
      - "192.168.1.23"

  tasks:
    - name: Connect to vCenter Server
      vmware_vm_shell:
        hostname: "{{ vcenter_hostname }}"
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        validate_certs: no
        cmd: echo "Connected to vCenter"
      delegate_to: localhost
      register: vcenter_connected

    - name: Deploy Master Node VM
      vmware_guest:
        hostname: "{{ vcenter_hostname }}"
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        validate_certs: no
        cluster: "{{ cluster_name }}"
        datastore: "{{ datastore_name }}"
        folder: "{{ vm_folder }}"
        name: "k8s-master"
        state: poweredon
        guest_id: ubuntu64Guest
        hardware:
          memory_mb: 2048
          num_cpus: 2
        networks:
          - name: "{{ network_name }}"
            mac: "00:50:56:00:00:01"
            ip: "{{ master_ip }}"
            netmask: "255.255.255.0"
            gateway: "192.168.1.1"
            dns_servers: "192.168.1.2"
        wait_for_ip_address: yes
        vm_extra_config:
          vcpu.hotadd: yes
        vmware_tools: yes
        vmware_folder_type: vm
        vmware_folder_name: "{{ vm_folder }}"
      delegate_to: localhost

    - name: Wait for Master Node to Boot
      wait_for:
        host: "{{ master_ip }}"
        port: 22
        delay: 10
        timeout: 300

    - name: Deploy Worker Node VMs
      vmware_guest:
        hostname: "{{ vcenter_hostname }}"
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        validate_certs: no
        cluster: "{{ cluster_name }}"
        datastore: "{{ datastore_name }}"
        folder: "{{ vm_folder }}"
        name: "k8s-worker-{{ loop.index }}"
        state: poweredon
        guest_id: ubuntu64Guest
        hardware:
          memory_mb: 2048
          num_cpus: 2
        networks:
          - name: "{{ network_name }}"
            mac: "00:50:56:00:00:0{{ loop.index + 1 }}"
            ip: "{{ worker_ips[loop.index] }}"
            netmask: "255.255.255.0"
            gateway: "192.168.1.1"
            dns_servers: "192.168.1.2"
        wait_for_ip_address: yes
        vm_extra_config:
          vcpu.hotadd: yes
        vmware_tools: yes
        vmware_folder_type: vm
        vmware_folder_name: "{{ vm_folder }}"
      loop: "{{ worker_ips }}"
      delegate_to: localhost

    - name: Wait for Worker Nodes to Boot
      wait_for:
        host: "{{ item }}"
        port: 22
        delay: 10
        timeout: 300
      loop: "{{ worker_ips }}"
